In [1]:
import numpy as np
import scipy.io
import pandas as pd
mat = scipy.io.loadmat('../data/traffic/traffic_dataset.mat')

In [2]:
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'tra_X_tr', 'tra_X_te', 'tra_Y_tr', 'tra_Y_te', 'tra_adj_mat'])

In [3]:
mat["tra_X_tr"][0][0]

<36x48 sparse matrix of type '<class 'numpy.float64'>'
	with 540 stored elements in Compressed Sparse Column format>

In [4]:
from scipy.sparse import csc_matrix
csc_matrix(mat["tra_X_tr"][0][0])

<36x48 sparse matrix of type '<class 'numpy.float64'>'
	with 540 stored elements in Compressed Sparse Column format>

In [5]:
type(mat["tra_X_tr"])

numpy.ndarray

In [6]:
type(mat["tra_X_tr"][0])

numpy.ndarray

In [7]:
type(mat["tra_X_tr"][0][0])

scipy.sparse._csc.csc_matrix

In [8]:
mat["tra_X_tr"][0][0].toarray()

array([[0.09248015, 0.09668379, 0.07006072, ..., 0.        , 0.        ,
        0.        ],
       [0.09715086, 0.10228865, 0.08173751, ..., 0.        , 0.        ,
        0.        ],
       [0.11536665, 0.11069594, 0.10555815, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.06772536, 0.08173751, 0.06118636, ..., 0.        , 0.        ,
        1.        ],
       [0.09388136, 0.11069594, 0.08827651, ..., 0.        , 0.        ,
        1.        ],
       [0.08313872, 0.06679122, 0.06725829, ..., 0.        , 1.        ,
        0.        ]])

In [9]:
mat["tra_X_tr"][0][0].toarray()[0]

array([0.09248015, 0.09668379, 0.07006072, 0.06585708, 0.07846801,
       0.07146193, 0.05418029, 0.04437179, 0.05464736, 0.05091079,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 3.        ,
       1.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        ])

In [10]:
mat["tra_X_tr"].shape

(1, 1261)

In [11]:
mat["tra_X_tr"][0].shape

(1261,)

In [12]:
mat["tra_X_tr"][0][0].shape

(36, 48)

In [13]:
mat["tra_Y_tr"].shape

(36, 1261)

In [14]:
cols = [
    "p1",
    "p2",
    "p3",
    "p4",
    "p5",
    "p6",
    "p7",
    "p8",
    "p9",
    "p10",
    "w1",
    "w2",
    "w3",
    "w4",
    "w5",
    "w6",
    "w7",
    "h0",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "h7",
    "h8",
    "h9",
    "h10",
    "h11",
    "h12",
    "h13",
    "h14",
    "h15",
    "h16",
    "h17",
    "h18",
    "h19",
    "h20",
    "h21",
    "h22",
    "h23",
    "d1",
    "d2",
    "d3",
    "d4",
    "#lanes",
    "name",
    "something"
]
len(cols)

48

In [15]:
# convert 3D to 2D for X
def convert3Dto2D(data):
    result = data[0][0].toarray()
    for i in range(1, len(data[0])):
        try:
            result = np.vstack((result, data[0][i].toarray()))
        except:
            print(f"err at {i}. result.shape: {result.shape}")
    return pd.DataFrame(result, columns=cols)    

In [16]:
X_train = convert3Dto2D(mat["tra_X_tr"])
X_test = convert3Dto2D(mat["tra_X_te"])

In [17]:
X_train.shape, X_train.head()

((45396, 48),
          p1        p2        p3        p4        p5        p6        p7  \
 0  0.092480  0.096684  0.070061  0.065857  0.078468  0.071462  0.054180   
 1  0.097151  0.102289  0.081738  0.076600  0.072396  0.067725  0.058851   
 2  0.115367  0.110696  0.105558  0.095283  0.067725  0.080336  0.062588   
 3  0.112097  0.102756  0.092013  0.083606  0.062121  0.070995  0.053713   
 4  0.127043  0.150864  0.131714  0.106025  0.099019  0.090612  0.069127   
 
          p8        p9       p10  ...  h21  h22  h23   d1   d2   d3   d4  \
 0  0.044372  0.054647  0.050911  ...  0.0  3.0  1.0  0.0  0.0  0.0  1.0   
 1  0.066324  0.059785  0.056983  ...  0.0  4.0  1.0  0.0  0.0  0.0  1.0   
 2  0.061653  0.055582  0.061653  ...  0.0  3.0  1.0  0.0  0.0  0.0  1.0   
 3  0.062588  0.053713  0.066791  ...  0.0  3.0  1.0  0.0  0.0  0.0  1.0   
 4  0.060719  0.060719  0.067258  ...  0.0  5.0  1.0  0.0  0.0  0.0  0.0   
 
    #lanes  name  something  
 0     0.0   0.0        0.0  
 1     0.0

In [18]:
y_train = mat["tra_Y_tr"].T.flatten()
y_test = mat["tra_Y_te"].T.flatten()

In [19]:
X_train.describe()
# at least, col39 is different scale

p1            p2            p3            p4            p5  \
count  45396.000000  45396.000000  45396.000000  45396.000000  45396.000000   
mean       0.303292      0.303242      0.303202      0.303184      0.303190   
std        0.199572      0.199618      0.199655      0.199674      0.199673   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.125175      0.124708      0.124708      0.124708      0.124708   
50%        0.292387      0.292387      0.292387      0.292387      0.292387   
75%        0.442317      0.442317      0.442317      0.442317      0.442317   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

                 p6            p7            p8            p9           p10  \
count  45396.000000  45396.000000  45396.000000  45396.000000  45396.000000   
mean       0.303224      0.303294      0.303406      0.303564      0.303775   
std        0.199654      0.199620      0.199577      0.199559      0.199574   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.124708      0.124708      0.125175      0.125175      0.125642   
50%        0.292387      0.292387      0.292854      0.292854      0.292854   
75%        0.442317      0.442317      0.442317      0.442317      0.442784   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

       ...           h21           h22           h23            d1  \
count  ...  45396.000000  45396.000000  45396.000000  45396.000000   
mean   ...      0.041237      3.527778      0.222222      0.388889   
std    ...      0.198840      0.832879      0.415744      0.487503   
min    ...      0.000000      1.000000      0.000000      0.000000   
25%    ...      0.000000      3.000000      0.000000      0.000000   
50%    ...      0.000000      4.000000      0.000000      0.000000   
75%    ...      0.000000      4.000000      0.000000      1.000000   
max    ...      1.000000      5.000000      1.000000      1.000000   

                 d2            d3            d4        #lanes          name  \
count  45396.000000  45396.000000  45396.000000  45396.000000  45396.000000   
mean       0.111111      0.277778      0.416667      0.305556      0.138889   
std        0.314273      0.447908      0.493012      0.460647      0.345834   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      1.000000      1.000000      1.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

          something  
count  45396.000000  
mean       0.138889  
std        0.345834  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000  

[8 rows x 48 columns]

In [20]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_norm = scaler.transform(X_train)
X_test_norm = scaler.transform(X_test)

In [21]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((45396, 48), (45396,), (30240, 48), (30240,))

In [22]:
np.array([[1,1,1],[2,2,2]]).T.flatten()

array([1, 2, 1, 2, 1, 2])

## Simple Regression without pre-processing

In [23]:
from sklearn.metrics import r2_score

In [24]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_norm, y_train)
print(r2_score(y_test, model.predict(X_test_norm)))

0.9506010985123429


In [25]:
from sklearn.linear_model import Lasso, BayesianRidge, ElasticNet
from sklearn.svm import SVR
from sklearn.linear_model import SGDRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor

models = [
    LinearRegression(),
    Lasso(),
    BayesianRidge(),
    ElasticNet(),
    # SVR(), # too much time
    SGDRegressor(),
    DecisionTreeRegressor(),
    MLPRegressor()
]

In [26]:
for model in models:
    model.fit(X_train_norm, y_train)
    print(model)
    print(r2_score(y_test, model.predict(X_test_norm)))
    print()

LinearRegression()
0.9506010985123429

Lasso()
-0.006971754422839149

BayesianRidge()
0.9506004858765027

ElasticNet()
-0.006971754422839149

SGDRegressor()
0.939812223528777

DecisionTreeRegressor()
0.9334362493209533

MLPRegressor()
0.9634289430512581



## Regression with dimension reduction by PCA

In [27]:
from sklearn.decomposition import PCA

n_components = 10
pca1 = PCA(n_components=n_components)
X_train_2d = pca1.fit_transform(X_train_norm)
pca2 = PCA(n_components=n_components)
X_test_2d = pca2.fit_transform(X_test_norm)

In [28]:
for model in models:
    model.fit(X_train_2d, y_train)
    print(model)
    print(r2_score(y_test, model.predict(X_test_2d)))
    print()

LinearRegression()
0.7005884871929011

Lasso()
-0.006971754422839149

BayesianRidge()
0.7005911256623365

ElasticNet()
-0.006971754422839149

SGDRegressor()
0.7006302694239634

DecisionTreeRegressor()
-0.18105927292907076

MLPRegressor()
0.5746822112955187

